name: Test Pipeline for FastAPI Book Project
run-name: ${{ github.actor }} is testing Lastest API Version
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pytest
        run: pytest || exit 1 # if test fails, fail the build
